### ISSUE TITLE
Doesn't need second button, potential name issue?

### ISSUE THREAD

**Issue by jeffgerstmann** [MiSTer-devel/Arcade-Pleiads_MiSTer#1]
Playing the 20190614 release - the core maps a second button for Barrier, which is appropriate for Phoenix, but this is a single-button game.

Should this be named Pleiads instead of Capitol? Capitol seems to be a bootleg or regional variant of Pleiads (which runs just fine on this core, by the way).

**Comment by alanswx** [comment]
How did you load Pleiads? Do you have a rom ini for it?

**Comment by jeffgerstmann** [comment]
Sorry, I slapped it together awhile ago and don't have a bat or ini for it. I'm pretty sure I just eyeballed the MAME source code for Phoenix and Pleiads and matched the order and sizes and such. It ran fine in the Phoenix core, runs fine in this one, too.

**Comment by alanswx** [comment]
Do you think I should just rename this repo? Or should I create another one for Pleiads? I have a working rom and script now.

**Comment by jeffgerstmann** [comment]
KLOV lists Capitol as "a German clone of Pleiads." MAME refers to Capitol a little more ambiguously, tagging the manufacturer with "bootleg?" on it. So I'd probably recommend Pleiads over Capitol.

People can always build the alternate sets and load them up separately if they want to see the alternate title screen for Capitol or see the US version with the Centuri license or whatever. MAME appears to have around eight different Pleiads sets to choose from.

**Comment by alanswx** [comment]
I am building the new cores with an “open rom”. Bruno is working on a script to dump all the rom variants that work. I will rename the repo I guess and change the file names and default loading.

**Comment by alanswx** [comment]
I believe I fixed both of these.

**Comment by jfroco** [comment]
> Playing the 20190614 release - the core maps a second button for Barrier, which is appropriate for Phoenix, but this is a single-button game.
> 
> Should this be named Pleiads instead of Capitol? Capitol seems to be a bootleg or regional variant of Pleiads (which runs just fine on this core, by the way).

Pleaids do have a second button: the warp button.
